### ISSUE TITLE
Airdrop Option Crashes Iridium

### ISSUE THREAD

**Issue by malhaar** [Co2333/Iridium#6]
Hey, 
when i decrypt ipa and try to airdop, it crash iridium app. Below are my specs.

iPad Pro 10.5 - iOS 14.3
Taurine - 1.1.1
Iridium - 1.2 Build 8

i may be wrong but could be a presentation bug on ipad. 

here:
https://github.com/Lakr233/Iridium/blob/05d142304dbaac06f1f17ca86a10c4a7716b2f02/Application/iridium/Interface/Decrypter/DecrypterViewController.swift#L164

this could be solution:
https://stackoverflow.com/a/29554248

check ipad and put in popover.

Hope it helps, 
Regards,

**Comment by Lakr233** [comment]
Updated to 1.2.15 and have a try~

**Comment by malhaar** [comment]
hey there, thank you for your efforts, i tried latest version but it still crashes. attaching crash report below for convenience. 

[text-5E64DE2A6D59-1.txt](https://github.com/Lakr233/Iridium/files/7918996/text-5E64DE2A6D59-1.txt)

Regards,

**Comment by Lakr233** [comment]
A crash that is happening to normal code won’t end up with no reg info like yours. 

```
Register values:
PC: 0x0                 LR: 0x0                 CPSR: 0x0
x0: 0x0                 x1: 0x0                 x2: 0x0
x3: 0x0                 x4: 0x0                 x5: 0x0
x6: 0x0                 x7: 0x0                 x8: 0x0
x9: 0x0                 x10: 0x0                x11: 0x0
x12: 0x0                x13: 0x0                x14: 0x0
x15: 0x0                x16: 0x0                x17: 0x0
x18: 0x0                x19: 0x0                x20: 0x0
x21: 0x0                x22: 0x0                x23: 0x0
x24: 0x0                x25: 0x0                x26: 0x0
x27: 0x0                x28: 0x0
```

This crash also happening on my own package manager, see
https://github.com/SailyTeam/Saily/issues/55
https://github.com/SailyTeam/Saily/issues/65

We are considering it as a bug on jailbreak not my app, and currently not going to fix it. But will keep up debugging if any possible hope was found.

**Comment by camieeh** [comment]
my ipad isn't jailbroken anymore so i have to assume it crashes when the share sheet appears? perhaps [this is of help](https://github.com/captinc/Batchomatic/blob/7899875431b6d38442a45707b53965fb2d06359d/Batchomatic.xm#L772)

**Comment by Lakr233** [comment]
> my ipad isn't jailbroken anymore so i have to assume it crashes when the share sheet appears? perhaps [this is of help](https://github.com/captinc/Batchomatic/blob/7899875431b6d38442a45707b53965fb2d06359d/Batchomatic.xm#L772)

![Simulator Screen Shot - iPad mini (6th generation) - 2022-01-29 at 23 32 49](https://user-images.githubusercontent.com/25259084/151666925-a970e7d9-03da-43b9-b6a0-5727ac5cfd06.png)

I'm prettpretty sure this is not the root case of this crash. I have tested it on iPads, and similar crash also happening on iPhones.

**Comment by camieeh** [comment]
huh interesting, is it another issue that only occurs in jailbroken state?

**Comment by Lakr233** [comment]
only occurs in some of the jailbreak, some of the devices, some of them, 100% crash if meet or works 100% fine if lucky.

**Comment by steliosaa** [comment]
iPadAir 2 (Wifi) [iPad5,3]
iPadOS 14.8
Checkra1n

App crashes on airdrop (I think it is because ipa isn't created. I cannot find the ipa anywhere with Filza)
Error happens since the begining, at the Target level 

=================================================================
=================================================================
Preparing operations...

TARGET:
/var/containers/Bundle/Application/B5FCF7B9-E371-4A6D-A8CF-C96ACE319F42/FlightradarFree.app
Swift/ErrorType.swift:200: Fatal error: Error raised at top level: Error Domain=NSCocoaErrorDomain Code=4 "The file “Flightradar24” doesn’t exist." UserInfo={NSSourceFilePathErrorKey=/var/containers/Bundle/Application/B5FCF7B9-E371-4A6D-A8CF-C96ACE319F42/FlightradarFree.app, NSUserStringVariant=(
    Copy
), NSDestinationFilePath=/var/mobile/Documents/wiki.qaq.iridium/Temporary/FBD42A40-5437-46E1-ABD9-13D8302B5A51/Payload/FlightradarFree.app, NSFilePath=/var/containers/Bundle/Application/B5FCF7B9-E371-4A6D-A8CF-C96ACE319F42/FlightradarFree.app, NSUnderlyingError=0x101308c70 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

Searching for mach objects...


[*] Selecting backend /Applications/iridium.app/fouldecrypt.krw



[*] Creating archive at /var/mobile/Documents/wiki.qaq.iridium/Packages/Flightradar24.se.resenatverket.FlightRadar24-Free.(8.18.1).ipa

......................... [100%]
 ++++++



[*] Cleaning temporary directory...
Swift/ErrorType.swift:200: Fatal error: Error raised at top level: Error Domain=NSCocoaErrorDomain Code=4 "“FBD42A40-5437-46E1-ABD9-13D8302B5A51” couldn’t be removed." UserInfo={NSUserStringVariant=(
    Remove
), NSFilePath=/var/mobile/Documents/wiki.qaq.iridium/Temporary/FBD42A40-5437-46E1-ABD9-13D8302B5A51, NSUnderlyingError=0x100a06960 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}


Resign and install may still need additional patch to package payload. You are on your own making those patches.



[Process Completed]

**Comment by camieeh** [comment]
@steliosaa your ios version is the first issue. i was told it works up to 14.3 at this time, @Lakr233 could update that in the readme

**Comment by steliosaa** [comment]
Oh I didn't know that! Thank you!

Any ideas what alternatives I have on my iOS version to decrypt my apps (not available on Mac appstore) so i can sideload on my M1?

**Comment by camieeh** [comment]
there are a few others but i can't name any

**Comment by steliosaa** [comment]
@schneelittchen I have found one that works on my iPad Air 2 (Wifi) iOS 14.8 Checkra1n, for anyone who is looking for it.
Repo: https://iosgods.com/repo
Package: iGameGod

Use the feature iGDecrypt under the Tools Tab of the iGameGod application
AirDrop the ipa via Filza under "var/mobile/Documents/Decrypted"
Run the ipa on MacOS Monterey via PlayCover
